name: Test

on:
  push:
    branches:
      - next
  pull_request:
    branches:
      - next

jobs:
  test:
    runs-on: ubuntu-latest

    name: Node

    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2.4.1

      - name: Install Node dependencies
        run: yarn --frozen-lockfile

      - run: yarn lint
      - run: yarn tsc
